### ISSUE TITLE
Route issue when trying to view a Paste - Redmine 1.3.0

### ISSUE THREAD

**Issue by real34** [commandprompt/redmine_pastebin#11]
When clicking on the title of a Paste from the index page, a route error is thrown.
Redmine version 1.3.0

Here is the log :

``` text
Processing PastesController#index (for 192.168.12.254 at 2012-01-31 08:26:17) [GET]
  Parameters: {"project_id"=>"ocitech-interne", "action"=>"index", "controller"=>"pastes"}
Rendering template within layouts/base
Rendering pastes/index
Completed in 61ms (View: 49, DB: 1) | 200 OK [http://xxx.com/projects/ocitech-interne/pastes]


Processing PastesController#show (for 192.168.12.254 at 2012-01-31 08:26:19) [GET]
  Parameters: {"action"=>"show", "id"=>"1", "controller"=>"pastes"}
Rendering template within layouts/base
Rendering pastes/show

ActionView::TemplateError (No route matches {:id=>#<Paste id: 1, text: "<?php\r\n/**\r\n * Ce script permet de crawler des urls...", lang: "PHP", author_id: 4, project_id: 40, created_on: "2012-01-31 08:25:03", updated_on: "2012-01-31 08:25:03", title: "Sitemap crawler">, :action=>"edit"}) on line #34 of vendor/plugins/redmine_pastebin/app/views/pastes/show.html.erb:
31: </div>
32: 
33: <p>
34: <%= manage_paste_links(@paste) %>
35: </p>
36: 
37: <%= render "sidebar" %>

    /usr/lib/ruby/vendor_ruby/action_controller/routing/route_set.rb:420:in `generate'
    /usr/lib/ruby/vendor_ruby/action_controller/url_rewriter.rb:218:in `rewrite_path'
    /usr/lib/ruby/vendor_ruby/action_controller/url_rewriter.rb:197:in `rewrite_url'
    /usr/lib/ruby/vendor_ruby/action_controller/url_rewriter.rb:175:in `rewrite'
    /usr/lib/ruby/vendor_ruby/action_controller/base.rb:625:in `url_for'
    /usr/lib/ruby/vendor_ruby/action_view/helpers/url_helper.rb:85:in `send'
    /usr/lib/ruby/vendor_ruby/action_view/helpers/url_helper.rb:85:in `url_for'
    /usr/lib/ruby/vendor_ruby/action_view/helpers/url_helper.rb:228:in `link_to'
    app/helpers/application_helper.rb:43:in `link_to_if_authorized'
    vendor/plugins/redmine_pastebin/app/helpers/pastes_helper.rb:93:in `edit_paste_link'
    vendor/plugins/redmine_pastebin/app/helpers/pastes_helper.rb:109:in `manage_paste_links'
    vendor/plugins/redmine_pastebin/app/views/pastes/show.html.erb:34
```

**Comment by toddwilson** [comment]
Also getting this one.

**Comment by a1exsh** [comment]
Works for me with 1.3-stable.  Can you guys please upgrade and try again?

**Comment by adrolter** [comment]
I'm also getting this on Redmine 1.4.1.stable.9557 (Mysql2)

# Fix:

Fixed by adding the line `map.resources :pastes, :action, :id` to the block in "vendor/plugins/redmine_pastebin/config/routes.rb"

``` ruby
ActionController::Routing::Routes.draw do |map|
  map.resources :pastes, :only => [:index, :show],
    :member => { :download => :get }
  map.resources :pastes, :path_prefix => '/projects/:project_id',
    :member => { :download => :get }
  map.resources :pastes, :action, :id
end
```

I had never touched a line of Ruby in my life, totally lucked out that it was such a simple fix.

**Comment by a1exsh** [comment]
A-ha, I've figured out the issue, thank you for being persistent about this.

The proper fix is included in this commit: https://github.com/commandprompt/redmine_pastebin/commit/13310468dfee2cc5096bb790701c6e6b53ecf44d#diff-5
